# English → Japanese Translation Error Annotation Pipeline

This notebook builds an error-annotated dataset of English→Japanese translations in three steps:

| Step | Description | Environment |
|------|-------------|-------------|
| **1** | Sample 500 sentence pairs from JParaCrawl | Local |
| **2** | Generate candidate translations with **Qwen2.5-7B-Instruct** (4-bit NF4) | Google Colab (free T4 GPU) |
| **3** | Annotate translation errors with **Gemini** (`gemini-3.1-flash-lite-preview`) via the Gemini API, processing 500 entries in batches of 10 | Google Colab (free T4 GPU) |

An LLM-as-judge (**Gemini `gemini-3.1-flash-lite-preview`**) scores each candidate for five error
categories (Terminology, Accuracy, Fluency/Grammar, Style/Register, Locale/Formatting) and assigns
a severity (major / minor / none).

**Inputs** (in `kb/`):
- `kb/eng-jap.tsv` — JParaCrawl sentence pairs

**Intermediate** (in `kb/`):
- `kb/candidates_for_annotation.jsonl` — Qwen2.5-7B-Instruct candidate translations

**Outputs** (in `kb/`):
- `kb/annotations_raw.jsonl` — full Gemini annotation results
- `kb/splits/error_id_train.jsonl` (300 rows) and `kb/splits/error_id_test.jsonl` (200 rows)

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## 1. Imports & Setup

In [ ]:
%pip install python-dotenv tqdm pandas --quiet

import pandas as pd
import json
import random
from tqdm.notebook import tqdm
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

RANDOM_SEED = 42
random.seed(RANDOM_SEED)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.4/469.4 kB 35.2 MB/s eta 0:00:00

## 2. Load JParaCrawl Sample *(Local)*

Read the full JParaCrawl TSV and sample 500 sentence pairs for annotation.
This step was run locally.

In [ ]:
JPARACRAWL_PATH = next(
    (p for p in [Path("/content/drive/MyDrive/GenAI Own/eng-jap.tsv"), Path("kb/eng-jap.tsv"), Path("../kb/eng-jap.tsv")] if p.exists()),
    None,
)
if JPARACRAWL_PATH is None:
    raise FileNotFoundError("Could not find eng-jap.tsv in any of the specified paths.")

print(f"Loading JParaCrawl from: {JPARACRAWL_PATH.resolve()}")

df_jpc = pd.read_csv(
    JPARACRAWL_PATH,
    sep="\t",
    header=None,
    names=["eng_id", "source_en", "jp_id", "reference_ja"],
    dtype=str,
).fillna("")

df_jpc["id"] = df_jpc["eng_id"] + "_" + df_jpc["jp_id"]

SAMPLE_SIZE = 500
df_sample = df_jpc.sample(n=SAMPLE_SIZE, random_state=RANDOM_SEED).reset_index(drop=True)

print(f"Sample shape: {df_sample.shape}")
df_sample[["id", "source_en", "reference_ja"]].head(3)

Loading JParaCrawl from: /content/drive/MyDrive/GenAI Own/eng-jap.tsv
Sample shape: (500, 5)

                id                                source_en      reference_ja
0     41423_204181  Don't keep company with such a bad boy.    そんな悪い子と友達になるな。
1  9354007_9678940         It wasn't our fault. Believe me.  私達のせいじゃないわ。信じてよ。
2     71054_149509                May I ask you a question?      質問をしてもいいですか。

## 2b. Install Translation Dependencies *(Google Colab — T4 GPU)*

> **Steps 2b–2g** were run on **Google Colab** with a free **T4 GPU** for faster inference.

Install `transformers`, `accelerate`, and `bitsandbytes` for 4-bit quantized Qwen2.5 inference.

In [ ]:
%pip install -q torch transformers accelerate bitsandbytes

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 11.1 MB/s eta 0:00:00

## 2c. Load Qwen2.5-7B-Instruct

Load the model with 4-bit NF4 quantization (`BitsAndBytesConfig`). Tokenizer is set to
`padding_side="left"` for correct batch-generation behaviour. Seeds are fixed for reproducibility.

In [ ]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

torch.manual_seed(42)
torch.cuda.manual_seed_all(42)

MODEL_ID = "Qwen/Qwen2.5-7B-Instruct"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)
tokenizer.padding_side = "left"
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True,
    torch_dtype=torch.float16,
)
model.eval()

gpu_name = torch.cuda.get_device_name(0)
vram_allocated = torch.cuda.memory_allocated(0) / 1024**3
vram_reserved = torch.cuda.memory_reserved(0) / 1024**3
print(f"GPU: {gpu_name}")
print(f"VRAM allocated: {vram_allocated:.2f} GB")
print(f"VRAM reserved:  {vram_reserved:.2f} GB")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/663 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/243 [00:00<?, ?B/s]

GPU: Tesla T4
VRAM allocated: 5.18 GB
VRAM reserved:  5.58 GB

## 2d. Translation Function

Define `translate_batch()` which applies Qwen's chat template with a translation system
prompt, generates with greedy decoding (`do_sample=False`), and returns only the newly
generated tokens. A sanity check translates the first sentence in `df_sample`.

In [ ]:
SYSTEM_MESSAGE = "You are a professional English-to-Japanese translator."

USER_TEMPLATE = (
    "Translate the following English text into Japanese. "
    "Output only the Japanese translation, nothing else.\n\n"
    "English: {source}"
)


def translate_batch(sources: list[str]) -> list[str]:
    conversations = []
    for src in sources:
        conversations.append([
            {"role": "system", "content": SYSTEM_MESSAGE},
            {"role": "user", "content": USER_TEMPLATE.format(source=src)},
        ])

    templated = tokenizer.apply_chat_template(
        conversations,
        add_generation_prompt=True,
        tokenize=False,
    )

    inputs = tokenizer(
        templated,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=1024,
    ).to(model.device)

    prompt_len = inputs["input_ids"].shape[1]

    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            do_sample=False,
            max_new_tokens=512,
            repetition_penalty=1.0,
            pad_token_id=tokenizer.pad_token_id,
        )

    generated_ids = output_ids[:, prompt_len:]
    translations = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)
    return [t.strip() for t in translations]


first_row = df_sample.iloc[0]
sanity = translate_batch([first_row["source_en"]])[0]
print(f"EN:        {first_row['source_en']}")
print(f"Candidate: {sanity}")
print(f"Reference: {first_row['reference_ja']}")

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

EN:        Don't keep company with such a bad boy.
Candidate: そんな不良と付き合わないでください。
Reference: そんな悪い子と友達になるな。

## 2e. Batch Inference

Translate all 500 sentences in batches of 4. Each result is written as a JSON line to
`candidates_for_annotation.jsonl` with annotation placeholder fields. The loop supports
resuming from a partial run by skipping already-completed IDs.

In [ ]:
import time

KB_DIR = JPARACRAWL_PATH.parent # Set KB_DIR to the parent directory of JPARACRAWL_PATH
OUTPUT_PATH = KB_DIR / "candidates_for_annotation.jsonl"
BATCH_SIZE = 4

# Ensure the directory exists before writing the file
OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

completed_ids: set[str] = set()
if OUTPUT_PATH.exists():
    with open(OUTPUT_PATH, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                completed_ids.add(json.loads(line)["id"])
    print(f"Resuming: {len(completed_ids)} rows already completed, skipping those.")

df_todo = df_sample[~df_sample["id"].isin(completed_ids)].reset_index(drop=True)
total_todo = len(df_todo)
print(f"Rows to translate: {total_todo}")

torch.manual_seed(42)
torch.cuda.manual_seed_all(42)

t_start = time.time()
done = 0

with open(OUTPUT_PATH, "a", encoding="utf-8") as fout:
    for batch_start in range(0, total_todo, BATCH_SIZE):
        batch = df_todo.iloc[batch_start : batch_start + BATCH_SIZE]
        sources = batch["source_en"].tolist()

        translations = translate_batch(sources)

        for (_, row), candidate_ja in zip(batch.iterrows(), translations):
            record = {
                "id": row["id"],
                "source_en": row["source_en"],
                "reference_ja": row["reference_ja"],
                "candidate_ja": candidate_ja,
                "has_error": None,
                "severity": None,
                "categories": [],
                "rationale": "",
            }
            fout.write(json.dumps(record, ensure_ascii=False) + "\n")

        fout.flush()
        done += len(batch)

        elapsed = time.time() - t_start
        rate = done / elapsed if elapsed > 0 else 0
        eta = (total_todo - done) / rate if rate > 0 else 0
        print(
            f"\r[{done}/{total_todo}] "
            f"{done / total_todo * 100:.1f}% | "
            f"{rate:.1f} examples/sec | "
            f"ETA: {eta:.0f}s",
            end="",
        )

elapsed_total = time.time() - t_start
print(f"\nFinished {done} translations in {elapsed_total:.1f}s")
print(f"Output: {OUTPUT_PATH.resolve()}")

Rows to translate: 500
[500/500] 100.0% | 1.0 examples/sec | ETA: 0s
Finished 500 translations in 491.3s
Output: /content/drive/MyDrive/GenAI Own/candidates_for_annotation.jsonl

## 2f. Verify Output

Read back the generated JSONL and display a random sample to confirm translations look reasonable.

In [ ]:
df_candidates_out = pd.read_json(OUTPUT_PATH, lines=True, dtype={"id": str})
print(f"Total records: {len(df_candidates_out)}")

sample_rows = df_candidates_out.sample(n=5, random_state=RANDOM_SEED)
display(sample_rows[["source_en", "reference_ja", "candidate_ja"]])

Total records: 500

,source_en,reference_ja,candidate_ja
361,Tom doesn't know that I hate him.,トムは私がトムを嫌ってることを知りません,トムは私に恨まれていることを知りません。
73,This bird can imitate the human voice.,この鳥は人の声を真似できるんだ。,この鳥は人間の声を模倣できます。
374,He writes to his mother every now and then.,彼は時折母親に手紙を書く。,彼は時々母に手紙を書きます。
155,Tom rushed to his room.,トムは自分の部屋にダッシュした。,トムは部屋へ急いで行きました。
104,They sought to punish him for his crime but he...,彼は罪を犯したので罰を加えようとしたが、彼は逃走した。,彼の罪を罰しようとしたが、彼は逃げた。

## 2g. Save Generation Config

Persist the model name, quantization settings, generation kwargs, and prompt templates
to `generation_config.json` for reproducibility.

In [ ]:
generation_config = {
    "model_name": MODEL_ID,
    "quantization": {
        "method": "bitsandbytes",
        "load_in_4bit": True,
        "bnb_4bit_quant_type": "nf4",
        "bnb_4bit_compute_dtype": "float16",
        "bnb_4bit_use_double_quant": True,
    },
    "generation_kwargs": {
        "do_sample": False,
        "max_new_tokens": 512,
        "repetition_penalty": 1.0,
    },
    "prompt_templates": {
        "system_message": SYSTEM_MESSAGE,
        "user_template": USER_TEMPLATE,
    },
    "tokenizer": {
        "padding_side": "left",
        "max_length": 1024,
        "truncation": True,
    },
    "seed": 42,
    "batch_size": BATCH_SIZE,
    "num_samples": len(df_sample),
}

KB_DIR = JPARACRAWL_PATH.parent # Set KB_DIR to the parent directory of JPARACRAWL_PATH
CONFIG_PATH = KB_DIR / "generation_config.json"
with open(CONFIG_PATH, "w", encoding="utf-8") as f:
    json.dump(generation_config, f, indent=2, ensure_ascii=False)

print(f"Saved generation config to {CONFIG_PATH.resolve()}")
print(json.dumps(generation_config, indent=2))

Saved generation config to /content/drive/MyDrive/GenAI Own/generation_config.json
{
  "model_name": "Qwen/Qwen2.5-7B-Instruct",
  "quantization": {
    "method": "bitsandbytes",
    "load_in_4bit": true,
    "bnb_4bit_quant_type": "nf4",
    "bnb_4bit_compute_dtype": "float16",
    "bnb_4bit_use_double_quant": true
  },
  "generation_kwargs": {
    "do_sample": false,
    "max_new_tokens": 512,
    "repetition_penalty": 1.0
  },
  "prompt_templates": {
    "system_message": "You are a professional English-to-Japanese translator.",
    "user_template": "Translate the following English text into Japanese. Output only the Japanese translation, nothing else.\n\nEnglish: {source}"
  },
  "tokenizer": {
    "padding_side": "left",
    "max_length": 1024,
    "truncation": true
  },
  "seed": 42,
  "batch_size": 4,
  "num_samples": 500
}

## 3. Load Candidate Translations *(Google Colab)*

> **Steps 3–5** were run on **Google Colab**, using the **Gemini API** (`gemini-3.1-flash-lite-preview`) to annotate all 500 error entries batch by batch.

Load the JSONL file containing Qwen2.5-7B-Instruct candidate translations and merge
with the JParaCrawl sample on `[id, source_en]`.

In [ ]:
CANDIDATES_PATH = JPARACRAWL_PATH.parent / "candidates_for_annotation.jsonl" # Use the parent directory for candidate path

if not CANDIDATES_PATH.exists(): # Check if the path exists
    raise FileNotFoundError(
        f"Could not find candidates.jsonl at {CANDIDATES_PATH.resolve()}"
    )

print(f"Loading candidates from: {CANDIDATES_PATH.resolve()}")

df_candidates = pd.read_json(CANDIDATES_PATH, lines=True, dtype={"id": str})
print(f"Candidates shape: {df_candidates.shape}")

df_merged = df_sample[["id", "source_en", "reference_ja"]].merge(
    df_candidates[["id", "source_en", "candidate_ja"]],
    on=["id", "source_en"],
    how="inner",
)

assert df_merged.isna().sum().sum() == 0, "Merge introduced null values!"
print(f"Merged shape: {df_merged.shape}")
df_merged.head(3)

Loading candidates from: /content/drive/MyDrive/GenAI Own/candidates_for_annotation.jsonl
Candidates shape: (500, 8)
Merged shape: (500, 4)

,id,source_en,reference_ja,candidate_ja
0,41423_204181,Don't keep company with such a bad boy.,そんな悪い子と友達になるな。,そんな不良と付き合わないでください。
1,9354007_9678940,It wasn't our fault. Believe me.,私達のせいじゃないわ。信じてよ。,それは私たちの faultではありません。信じてください。
2,71054_149509,May I ask you a question?,質問をしてもいいですか。,質問させていただけますか？

## 4. Gemini API Setup & Batch Annotation

Configure the **Gemini API** (`gemini-3.1-flash-lite-preview`) with a structured system prompt
and annotate all 500 candidate translations in batches of 10, with a 60-second cooldown
between batches to stay within API rate limits.

In [3]:
import google.generativeai as genai
import json
import time
import os
from google.colab import userdata

# 1. Bypass Colab's internal proxy
os.environ['NO_PROXY'] = 'generativelanguage.googleapis.com'

# 2. Configure the API
try:
    GOOGLE_API_KEY = userdata.get('GEMINI_API_KEY')
    genai.configure(api_key=GOOGLE_API_KEY, transport="rest")
except userdata.SecretNotFoundError:
    print("Error: Please set the 'GEMINI_API_KEY' secret in the Colab sidebar.")

# 3. Setup the Model
SYSTEM_INSTRUCTION = """
You are a professional English→Japanese translation quality evaluator.
Given an English source sentence, a candidate Japanese translation, and a reference Japanese translation, evaluate the candidate for errors.

### Error categories
1. Terminology – incorrect or inconsistent term usage
2. Accuracy – meaning additions, omissions, or distortions
3. Fluency/Grammar – unnatural phrasing, grammatical mistakes
4. Style/Register – inappropriate formality level or tone
5. Locale/Formatting – wrong number formats, date formats, punctuation conventions

### Severity
- major – the error changes meaning or seriously hinders comprehension
- minor – the error is noticeable but does not change core meaning
- none – no meaningful error detected

### Rules
- Do NOT penalise stylistic differences if the core meaning is preserved correctly.
- If `has_error` is false, `severity` MUST be "none" and `categories` MUST be [].
- Return ONLY valid JSON matching this schema:
{
  "has_error": true | false,
  "severity": "major" | "minor" | "none",
  "categories": ["Category Name"],
  "rationale": "string"
}
"""

model = genai.GenerativeModel(
    model_name='gemini-3.1-flash-lite-preview',
    system_instruction=SYSTEM_INSTRUCTION,
    generation_config={"response_mime_type": "application/json"}
)

# 4. The Batch Processing Function
def process_in_batches(input_file, output_file, batch_size=10):
    print(f"Starting batch annotation. Reading from {input_file}...")

    # Read all lines from the file
    with open(input_file, 'r', encoding='utf-8') as f:
        lines = [line.strip() for line in f if line.strip()]

    total_entries = len(lines)
    print(f"Total entries to process: {total_entries}")

    # Figure out where to resume if the script was interrupted
    processed_count = 0
    if os.path.exists(output_file):
        with open(output_file, 'r', encoding='utf-8') as f:
            processed_count = sum(1 for line in f)
        print(f"Found existing output file. Resuming from entry {processed_count}...")

    # Process the remaining lines in chunks
    for i in range(processed_count, total_entries, batch_size):
        chunk = lines[i : i + batch_size]
        print(f"\n--- Processing Batch {i//batch_size + 1} (Entries {i+1} to {i + len(chunk)}) ---")

        # Open in "append" mode ('a') so we don't overwrite previous batches
        with open(output_file, 'a', encoding='utf-8') as outfile:
            for line in chunk:
                data = json.loads(line)
                prompt = (
                    f"Source (EN): {data.get('source_en')}\n"
                    f"Candidate (JA): {data.get('candidate_ja')}\n"
                    f"Reference (JA): {data.get('reference_ja')}"
                )

                # Retry loop for individual timeouts
                retries = 3
                for attempt in range(retries):
                    try:
                        response = model.generate_content(prompt)
                        evaluation = json.loads(response.text)

                        data['has_error'] = evaluation.get('has_error')
                        data['severity'] = evaluation.get('severity')
                        data['categories'] = evaluation.get('categories', [])
                        data['rationale'] = evaluation.get('rationale', '')

                        outfile.write(json.dumps(data, ensure_ascii=False) + '\n')
                        print(f"  ✓ Processed ID: {data.get('id', 'Unknown')}")
                        break # Break out of retry loop on success

                    except Exception as e:
                        if attempt < retries - 1:
                            print(f"  ! Error on ID {data.get('id')}. Retrying... ({e})")
                            time.sleep(5) # Brief pause before retry
                        else:
                            print(f"  X Failed to process ID {data.get('id')}. Skipping. Error: {e}")

        # After completing a batch, check if there are more items to process
        if i + batch_size < total_entries:
            print("Batch complete. Sleeping for 60 seconds to reset API rate limit...")
            time.sleep(60)

    print("\nAll entries processed successfully!")

# 5. Run the Script
INPUT_PATH = '/content/drive/MyDrive/GenAI Own/candidates_for_annotation.jsonl'
OUTPUT_PATH = '/content/drive/MyDrive/GenAI Own/gemini_annotated_results.jsonl'

process_in_batches(INPUT_PATH, OUTPUT_PATH, batch_size=10)

Starting batch annotation. Reading from /content/drive/MyDrive/GenAI Own/candidates_for_annotation.jsonl...
Total entries to process: 500
Found existing output file. Resuming from entry 0...

--- Processing Batch 1 (Entries 1 to 10) ---
  ✓ Processed ID: 41423_204181
  ✓ Processed ID: 9354007_9678940
  ✓ Processed ID: 71054_149509
  ✓ Processed ID: 264505_150052
  ✓ Processed ID: 9193501_11563342
  ✓ Processed ID: 283323_120685
  ✓ Processed ID: 35902_198709
  ✓ Processed ID: 43729_206481
  ✓ Processed ID: 279489_124505
  ✓ Processed ID: 12120017_3120246
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 2 (Entries 11 to 20) ---
  ✓ Processed ID: 298089_105599
  ✓ Processed ID: 61271_223936
  ✓ Processed ID: 65550_228196
  ✓ Processed ID: 5747794_5748453
  ✓ Processed ID: 1500305_137771
  ✓ Processed ID: 293864_1383978

ERROR:tornado.access:503 POST /v1beta/models/gemini-3.1-flash-lite-preview:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 10536.94ms

  ✓ Processed ID: 6574071_6089608

ERROR:tornado.access:503 POST /v1beta/models/gemini-3.1-flash-lite-preview:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 5508.16ms

  ✓ Processed ID: 73350_235969
  ✓ Processed ID: 314361_89350
  ✓ Processed ID: 1485672_201080
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 3 (Entries 21 to 30) ---
  ✓ Processed ID: 275311_137924
  ✓ Processed ID: 239900_174569
  ✓ Processed ID: 263362_151194
  ✓ Processed ID: 297207_106480
  ✓ Processed ID: 49396_212117
  ✓ Processed ID: 256155_158375
  ✓ Processed ID: 39574_202363
  ✓ Processed ID: 10465226_231952
  ✓ Processed ID: 49114_211837
  ✓ Processed ID: 10937149_10937150
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 4 (Entries 31 to 40) ---
  ✓ Processed ID: 36021_198826
  ✓ Processed ID: 53889_216584
  ✓ Processed ID: 269890_144674
  ✓ Processed ID: 502362_502354
  ✓ Processed ID: 249611_164896
  ✓ Processed ID: 1108772_4713
  ✓ Processed ID: 58672_221348
  ✓ Processed ID: 38407_201200
  ✓ Processed ID: 908915_186898
  ✓ Processed ID: 57656_220336
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 5 (Entries 41 to 50) ---
  ✓ Processed ID: 244097_170387
  ✓ Processed ID: 10152135_8482162
  ✓ Processed ID: 245481_169006
  ✓ Processed ID: 46846_209584
  ✓ Processed ID: 2819613_10290184
  ✓ Processed ID: 54345_217038
  ✓ Processed ID: 2733564_2469523
  ✓ Processed ID: 50793_213507
  ✓ Processed ID: 10005463_10006960
  ✓ Processed ID: 1178694_10644046
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 6 (Entries 51 to 60) ---
  ✓ Processed ID: 6660564_10961266
  ✓ Processed ID: 318037_85676
  ✓ Processed ID: 10306422_10303645
  ✓ Processed ID: 297627_106059
  ✓ Processed ID: 7763844_9434932
  ✓ Processed ID: 315881_87826
  ✓ Processed ID: 3446787_10199987
  ✓ Processed ID: 4190431_4587160
  ✓ Processed ID: 1449774_198225
  ✓ Processed ID: 433299_433297
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 7 (Entries 61 to 70) ---
  ✓ Processed ID: 25612_188469
  ✓ Processed ID: 294149_109541
  ✓ Processed ID: 7492525_156302
  ✓ Processed ID: 2355816_2349246
  ✓ Processed ID: 324853_78863
  ✓ Processed ID: 2712845_11485194
  ✓ Processed ID: 8855658_11637655
  ✓ Processed ID: 10192983_10193338
  ✓ Processed ID: 45686_208428
  ✓ Processed ID: 69264_231897
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 8 (Entries 71 to 80) ---
  ✓ Processed ID: 41708_204466
  ✓ Processed ID: 7022028_3360030
  ✓ Processed ID: 276171_137065
  ✓ Processed ID: 57820_220496
  ✓ Processed ID: 11070022_2944723
  ✓ Processed ID: 2111_5296
  ✓ Processed ID: 53292_215991
  ✓ Processed ID: 13798642_1182047
  ✓ Processed ID: 657379_171951
  ✓ Processed ID: 313139_90573
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 9 (Entries 81 to 90) ---
  ✓ Processed ID: 443159_8752827
  ✓ Processed ID: 313577_10050458
  ✓ Processed ID: 485099_200437
  ✓ Processed ID: 1040671_1131281
  ✓ Processed ID: 244711_169775
  ✓ Processed ID: 16833_177981
  ✓ Processed ID: 320990_11110427
  ✓ Processed ID: 62691_225353
  ✓ Processed ID: 10733834_12351442
  ✓ Processed ID: 2249201_8814813
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 10 (Entries 91 to 100) ---
  ✓ Processed ID: 38789_201579
  ✓ Processed ID: 5578798_9176902
  ✓ Processed ID: 258194_10028676
  ✓ Processed ID: 320344_83372
  ✓ Processed ID: 298373_105316
  ✓ Processed ID: 310220_93488
  ✓ Processed ID: 7924334_113371
  ✓ Processed ID: 10061827_9966235
  ✓ Processed ID: 49256_211977
  ✓ Processed ID: 853133_3495554
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 11 (Entries 101 to 110) ---
  ✓ Processed ID: 8980370_167843
  ✓ Processed ID: 1128006_3597466
  ✓ Processed ID: 253569_160949
  ✓ Processed ID: 324027_79691
  ✓ Processed ID: 296841_106845
  ✓ Processed ID: 3060760_79062
  ✓ Processed ID: 12443677_9563956
  ✓ Processed ID: 280946_123054
  ✓ Processed ID: 1315900_109040
  ✓ Processed ID: 6795006_8743203
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 12 (Entries 111 to 120) ---
  ✓ Processed ID: 318685_85027
  ✓ Processed ID: 255784_9770649
  ✓ Processed ID: 36149_198953
  ✓ Processed ID: 254064_160457
  ✓ Processed ID: 8863296_12098590
  ✓ Processed ID: 243545_170935
  ✓ Processed ID: 293410_110278
  ✓ Processed ID: 255268_159256
  ✓ Processed ID: 11045324_12167739
  ✓ Processed ID: 5030415_3134900
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 13 (Entries 121 to 130) ---
  ✓ Processed ID: 48244_210973
  ✓ Processed ID: 28969_191807
  ✓ Processed ID: 245234_169252
  ✓ Processed ID: 11837478_12670151
  ✓ Processed ID: 12348098_11853803
  ✓ Processed ID: 5438405_13192387
  ✓ Processed ID: 276592_136522
  ✓ Processed ID: 13474103_12868823
  ✓ Processed ID: 260348_154195
  ✓ Processed ID: 265927_9308330
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 14 (Entries 131 to 140) ---
  ✓ Processed ID: 2129925_8597478
  ✓ Processed ID: 6704036_11195685
  ✓ Processed ID: 248638_165866
  ✓ Processed ID: 10124115_8655980
  ✓ Processed ID: 281406_122597
  ✓ Processed ID: 329059_74660
  ✓ Processed ID: 536948_521680
  ✓ Processed ID: 901560_112957
  ✓ Processed ID: 1054587_2113349
  ✓ Processed ID: 267817_146744
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 15 (Entries 141 to 150) ---
  ✓ Processed ID: 13079747_188338
  ✓ Processed ID: 381381_102229
  ✓ Processed ID: 455941_1142904
  ✓ Processed ID: 9735302_9735317
  ✓ Processed ID: 1785436_1785434
  ✓ Processed ID: 322906_80809
  ✓ Processed ID: 292793_110893
  ✓ Processed ID: 266196_148363
  ✓ Processed ID: 6434833_12120940
  ✓ Processed ID: 953632_1563692
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 16 (Entries 151 to 160) ---
  ✓ Processed ID: 49073_211796
  ✓ Processed ID: 12278336_12003632
  ✓ Processed ID: 27626_142719
  ✓ Processed ID: 283950_119712
  ✓ Processed ID: 274105_140468
  ✓ Processed ID: 9192375_9192397
  ✓ Processed ID: 6243771_8218448
  ✓ Processed ID: 7520728_8762167
  ✓ Processed ID: 646984_227543
  ✓ Processed ID: 43047_205801
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 17 (Entries 161 to 170) ---
  ✓ Processed ID: 254533_8218410
  ✓ Processed ID: 3425650_189032
  ✓ Processed ID: 240944_173526
  ✓ Processed ID: 55299_217990
  ✓ Processed ID: 3618991_12143593
  ✓ Processed ID: 10778168_83156
  ✓ Processed ID: 1025546_2577612
  ✓ Processed ID: 313876_89839
  ✓ Processed ID: 311789_91923
  ✓ Processed ID: 3168495_8828806
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 18 (Entries 171 to 180) ---
  ✓ Processed ID: 63274_225936
  ✓ Processed ID: 6480881_8075158
  ✓ Processed ID: 323850_79867
  ✓ Processed ID: 243504_170976
  ✓ Processed ID: 9211382_4561484
  ✓ Processed ID: 32635_195507
  ✓ Processed ID: 2549353_3366895
  ✓ Processed ID: 326765_76955
  ✓ Processed ID: 300714_102980
  ✓ Processed ID: 310278_1013515
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 19 (Entries 181 to 190) ---
  ✓ Processed ID: 26811_189658
  ✓ Processed ID: 620691_198152
  ✓ Processed ID: 2387611_2925491
  ✓ Processed ID: 10094023_10097770
  ✓ Processed ID: 7258087_126100
  ✓ Processed ID: 62283_224948
  ✓ Processed ID: 8614268_8625486
  ✓ Processed ID: 63012_225675
  ✓ Processed ID: 255333_11553271
  ✓ Processed ID: 256845_157686
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 20 (Entries 191 to 200) ---
  ✓ Processed ID: 268724_145838
  ✓ Processed ID: 71047_10154403
  ✓ Processed ID: 5043074_8663737
  ✓ Processed ID: 249136_165369
  ✓ Processed ID: 44922_9547366
  ✓ Processed ID: 254686_159836
  ✓ Processed ID: 1212732_146982
  ✓ Processed ID: 843920_124215
  ✓ Processed ID: 317967_85746
  ✓ Processed ID: 296194_107492
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 21 (Entries 201 to 210) ---
  ✓ Processed ID: 62491_225156
  ✓ Processed ID: 22737_185606
  ✓ Processed ID: 2661475_11491197
  ✓ Processed ID: 25994_188855
  ✓ Processed ID: 49761_160310
  ✓ Processed ID: 6237432_12012583
  ✓ Processed ID: 290194_113479
  ✓ Processed ID: 1812363_1812367
  ✓ Processed ID: 9534012_226807
  ✓ Processed ID: 252119_13201668
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 22 (Entries 211 to 220) ---
  ✓ Processed ID: 4550442_3052841
  ✓ Processed ID: 72742_235362
  ✓ Processed ID: 4352322_4212224
  ✓ Processed ID: 322845_80870
  ✓ Processed ID: 32147_194973
  ✓ Processed ID: 10720791_10714049
  ✓ Processed ID: 59810_222481
  ✓ Processed ID: 329136_74583
  ✓ Processed ID: 249815_164692
  ✓ Processed ID: 3182876_3169535
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 23 (Entries 221 to 230) ---
  ✓ Processed ID: 28502_191340
  ✓ Processed ID: 1890907_2311963
  ✓ Processed ID: 24783_187645
  ✓ Processed ID: 292818_110868
  ✓ Processed ID: 69298_231930
  ✓ Processed ID: 43457_206211
  ✓ Processed ID: 260767_153776
  ✓ Processed ID: 11049405_11049410
  ✓ Processed ID: 3327388_8960515
  ✓ Processed ID: 277311_126779
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 24 (Entries 231 to 240) ---
  ✓ Processed ID: 9192553_10218887
  ✓ Processed ID: 252082_162432
  ✓ Processed ID: 57531_220211
  ✓ Processed ID: 6531690_8734062
  ✓ Processed ID: 46297_209037
  ✓ Processed ID: 1886156_10125556
  ✓ Processed ID: 25537_164338
  ✓ Processed ID: 244263_170221
  ✓ Processed ID: 318448_85265
  ✓ Processed ID: 264288_150269
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 25 (Entries 241 to 250) ---
  ✓ Processed ID: 240440_12510840
  ✓ Processed ID: 24885_358297
  ✓ Processed ID: 322143_81572
  ✓ Processed ID: 1739968_2245826
  ✓ Processed ID: 269172_145391
  ✓ Processed ID: 8962588_12596957
  ✓ Processed ID: 466971_1795045
  ✓ Processed ID: 305456_97495
  ✓ Processed ID: 238317_176148
  ✓ Processed ID: 288151_115519
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 26 (Entries 251 to 260) ---
  ✓ Processed ID: 62212_224877
  ✓ Processed ID: 63330_225991
  ✓ Processed ID: 3008014_9824270
  ✓ Processed ID: 4588590_2706821
  ✓ Processed ID: 282502_121503
  ✓ Processed ID: 238924_175541
  ✓ Processed ID: 3318983_10309112
  ✓ Processed ID: 245680_9983878
  ✓ Processed ID: 10789575_10556970
  ✓ Processed ID: 240174_174294
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 27 (Entries 261 to 270) ---
  ✓ Processed ID: 237889_176574
  ✓ Processed ID: 48918_211641
  ✓ Processed ID: 1292208_2293860
  ✓ Processed ID: 12489851_12489588
  ✓ Processed ID: 252231_162283
  ✓ Processed ID: 953604_1558341
  ✓ Processed ID: 3147964_8652502
  ✓ Processed ID: 2733557_91632
  ✓ Processed ID: 5967741_188826
  ✓ Processed ID: 41758_204518
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 28 (Entries 271 to 280) ---
  ✓ Processed ID: 6345434_12954934
  ✓ Processed ID: 4663150_8983525
  ✓ Processed ID: 298399_105289
  ✓ Processed ID: 1887352_2183407
  ✓ Processed ID: 40609_203371
  ✓ Processed ID: 5852258_12412197
  ✓ Processed ID: 1243567_118688
  ✓ Processed ID: 3733190_8534707
  ✓ Processed ID: 5966430_1486289
  ✓ Processed ID: 66214_161417
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 29 (Entries 281 to 290) ---
  ✓ Processed ID: 6558267_8588664
  ✓ Processed ID: 50877_213590
  ✓ Processed ID: 13569852_3447238
  ✓ Processed ID: 1776891_1776896
  ✓ Processed ID: 881397_4900382
  ✓ Processed ID: 6434728_11686095
  ✓ Processed ID: 299254_104437
  ✓ Processed ID: 16322_9029750
  ✓ Processed ID: 317001_86710
  ✓ Processed ID: 2248502_3496706
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 30 (Entries 291 to 300) ---
  ✓ Processed ID: 1099151_185404
  ✓ Processed ID: 251411_163101
  ✓ Processed ID: 61740_224405
  ✓ Processed ID: 50210_212925
  ✓ Processed ID: 284539_119123
  ✓ Processed ID: 324795_78922
  ✓ Processed ID: 53885_216581
  ✓ Processed ID: 19925_182805
  ✓ Processed ID: 439628_439627
  ✓ Processed ID: 298066_105623
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 31 (Entries 301 to 310) ---
  ✓ Processed ID: 290750_112926
  ✓ Processed ID: 271020_143547
  ✓ Processed ID: 1439953_2366944
  ✓ Processed ID: 313243_90470
  ✓ Processed ID: 286803_116865
  ✓ Processed ID: 303007_100690
  ✓ Processed ID: 1080127_1518090
  ✓ Processed ID: 61126_223790
  ✓ Processed ID: 29020_173493
  ✓ Processed ID: 275221_138014
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 32 (Entries 311 to 320) ---
  ✓ Processed ID: 254424_160097
  ✓ Processed ID: 319128_84587
  ✓ Processed ID: 243112_9032587
  ✓ Processed ID: 276179_137057
  ✓ Processed ID: 309030_94675
  ✓ Processed ID: 6354006_11609763
  ✓ Processed ID: 6049413_141924
  ✓ Processed ID: 8459293_1655168
  ✓ Processed ID: 27832_190672
  ✓ Processed ID: 8856583_11018042
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 33 (Entries 321 to 330) ---
  ✓ Processed ID: 7724789_7725410
  ✓ Processed ID: 38145_200941
  ✓ Processed ID: 328211_75507
  ✓ Processed ID: 1774_182337
  ✓ Processed ID: 258885_155653
  ✓ Processed ID: 284071_101601
  ✓ Processed ID: 1499885_10618148
  ✓ Processed ID: 1456526_156419
  ✓ Processed ID: 7910916_1181508
  ✓ Processed ID: 314514_89192
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 34 (Entries 331 to 340) ---
  ✓ Processed ID: 11175755_11175753
  ✓ Processed ID: 1954866_5185666
  ✓ Processed ID: 286747_116920
  ✓ Processed ID: 434610_3283009
  ✓ Processed ID: 35394_198201
  ✓ Processed ID: 2315178_2853024
  ✓ Processed ID: 30489_193324
  ✓ Processed ID: 327086_5955865
  ✓ Processed ID: 7174666_3556198
  ✓ Processed ID: 449095_10630513
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 35 (Entries 341 to 350) ---
  ✓ Processed ID: 31469_194296
  ✓ Processed ID: 34044_1097015
  ✓ Processed ID: 42375_205133
  ✓ Processed ID: 256121_158409
  ✓ Processed ID: 24414_187277
  ✓ Processed ID: 6874112_137068
  ✓ Processed ID: 7846353_11797107
  ✓ Processed ID: 10701842_107077
  ✓ Processed ID: 3012460_13293951
  ✓ Processed ID: 50553_213268
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 36 (Entries 351 to 360) ---
  ✓ Processed ID: 2410351_2411684
  ✓ Processed ID: 15968_177120
  ✓ Processed ID: 1045540_1046234
  ✓ Processed ID: 1848835_219262
  ✓ Processed ID: 7910955_1153081
  ✓ Processed ID: 649705_649704
  ✓ Processed ID: 480576_480598
  ✓ Processed ID: 319761_83953
  ✓ Processed ID: 309432_94274
  ✓ Processed ID: 326968_76752
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 37 (Entries 361 to 370) ---
  ✓ Processed ID: 253367_161151
  ✓ Processed ID: 6261925_11402362
  ✓ Processed ID: 7518272_226971
  ✓ Processed ID: 9325796_11782640
  ✓ Processed ID: 311877_91835
  ✓ Processed ID: 395036_82157
  ✓ Processed ID: 50619_227866
  ✓ Processed ID: 318150_229334
  ✓ Processed ID: 255939_158590
  ✓ Processed ID: 302477_101219
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 38 (Entries 371 to 380) ---
  ✓ Processed ID: 388734_95321
  ✓ Processed ID: 323905_79812
  ✓ Processed ID: 10463187_10463185
  ✓ Processed ID: 1260372_10758621
  ✓ Processed ID: 298415_105271
  ✓ Processed ID: 4597423_83400
  ✓ Processed ID: 263130_151426
  ✓ Processed ID: 277951_126040
  ✓ Processed ID: 26093_188947
  ✓ Processed ID: 8977971_12757739
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 39 (Entries 381 to 390) ---
  ✓ Processed ID: 261887_152661
  ✓ Processed ID: 61768_1175825
  ✓ Processed ID: 51391_214101
  ✓ Processed ID: 13065298_11045416
  ✓ Processed ID: 274396_140156
  ✓ Processed ID: 16094_177245
  ✓ Processed ID: 22933_185801
  ✓ Processed ID: 283490_120520
  ✓ Processed ID: 3359938_11479927
  ✓ Processed ID: 1319173_3461676
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 40 (Entries 391 to 400) ---
  ✓ Processed ID: 57435_220116
  ✓ Processed ID: 324975_78741
  ✓ Processed ID: 2541278_11013767
  ✓ Processed ID: 282981_121027
  ✓ Processed ID: 1093151_1486407
  ✓ Processed ID: 270383_144186
  ✓ Processed ID: 10332755_10335149
  ✓ Processed ID: 264046_150511
  ✓ Processed ID: 400955_400954
  ✓ Processed ID: 249888_164619
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 41 (Entries 401 to 410) ---
  ✓ Processed ID: 2481727_2875709
  ✓ Processed ID: 325779_77939
  ✓ Processed ID: 433521_169172
  ✓ Processed ID: 1401642_101430
  ✓ Processed ID: 6263056_8875946
  ✓ Processed ID: 6248944_13152664
  ✓ Processed ID: 25629_188486
  ✓ Processed ID: 321203_82513
  ✓ Processed ID: 6346333_10124189
  ✓ Processed ID: 4415212_12022238
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 42 (Entries 411 to 420) ---
  ✓ Processed ID: 72519_235140
  ✓ Processed ID: 2279303_2385311
  ✓ Processed ID: 313887_89828
  ✓ Processed ID: 280930_123070
  ✓ Processed ID: 59974_222645
  ✓ Processed ID: 262717_151838
  ✓ Processed ID: 68012_230644
  ✓ Processed ID: 65088_227735
  ✓ Processed ID: 2252512_2252491
  ✓ Processed ID: 294508_109182
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 43 (Entries 421 to 430) ---
  ✓ Processed ID: 13693644_10901651
  ✓ Processed ID: 253114_10106895
  ✓ Processed ID: 10720797_10705034
  ✓ Processed ID: 281268_122734
  ✓ Processed ID: 41538_225898
  ✓ Processed ID: 31129_193961
  ✓ Processed ID: 289165_114506
  ✓ Processed ID: 22450_185318
  ✓ Processed ID: 318177_85536
  ✓ Processed ID: 257272_83566
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 44 (Entries 431 to 440) ---
  ✓ Processed ID: 271603_142965
  ✓ Processed ID: 314034_1181495
  ✓ Processed ID: 310108_93599
  ✓ Processed ID: 64823_227471
  ✓ Processed ID: 260336_154207
  ✓ Processed ID: 319771_83945
  ✓ Processed ID: 65286_227933
  ✓ Processed ID: 59276_221950
  ✓ Processed ID: 277733_126259
  ✓ Processed ID: 36976_199772
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 45 (Entries 441 to 450) ---
  ✓ Processed ID: 278324_125668
  ✓ Processed ID: 267309_147252
  ✓ Processed ID: 16795_2710673
  ✓ Processed ID: 7438215_8218412
  ✓ Processed ID: 6678554_9668000
  ✓ Processed ID: 296117_107568
  ✓ Processed ID: 33013_10109257
  ✓ Processed ID: 321538_82177
  ✓ Processed ID: 24426_187289
  ✓ Processed ID: 9365984_2182845
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 46 (Entries 451 to 460) ---
  ✓ Processed ID: 2540417_5348192
  ✓ Processed ID: 238748_175717
  ✓ Processed ID: 4666926_8400567
  ✓ Processed ID: 318667_85046
  ✓ Processed ID: 276622_136294
  ✓ Processed ID: 29953_83299
  ✓ Processed ID: 10221543_11571138
  ✓ Processed ID: 4665853_8613547
  ✓ Processed ID: 45864_208605
  ✓ Processed ID: 72423_235046
Batch complete. Sleeping for 60 seconds to reset API rate limit...

--- Processing Batch 47 (Entries 461 to 470) ---
  ✓ Processed ID: 72049_234671
  ✓ Processed ID: 21729_184601
  ✓ Processed ID: 274179_140394
  ✓ Processed ID: 35893_1658388
  ✓ Processed ID: 317715_85996
  ✓ Processed ID: 266625_147935
  ✓ Processed ID: 258978_155560
  ✓ Processed ID: 244839_169647
  ✓ Processed ID: 11158947_177883

WARNING:tornado.access:429 POST /v1beta/models/gemini-3.1-flash-lite-preview:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 280.18ms

  ! Error on ID 285692_117972. Retrying... (429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 500, model: gemini-3.1-flash-lite
Please retry in 46.610786658s.)
  ✓ Processed ID: 285692_117972

WARNING:tornado.access:429 POST /v1beta/models/gemini-3.1-flash-lite-preview:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 279.18ms

  ! Error on ID 7240911_10746979. Retrying... (429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 500, model: gemini-3.1-flash-lite
Please retry in 35.868431059s.)

WARNING:tornado.access:429 POST /v1beta/models/gemini-3.1-flash-lite-preview:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.57ms

  ! Error on ID 7240911_10746979. Retrying... (429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 500, model: gemini-3.1-flash-lite
Please retry in 30.5772639s.)

WARNING:tornado.access:429 POST /v1beta/models/gemini-3.1-flash-lite-preview:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 304.41ms

  X Failed to process ID 7240911_10746979. Skipping. Error: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 500, model: gemini-3.1-flash-lite
Please retry in 25.26985882s.

WARNING:tornado.access:429 POST /v1beta/models/gemini-3.1-flash-lite-preview:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 279.28ms

  ! Error on ID 36018_198822. Retrying... (429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 500, model: gemini-3.1-flash-lite
Please retry in 24.966724382s.)

WARNING:tornado.access:429 POST /v1beta/models/gemini-3.1-flash-lite-preview:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 279.26ms

  ! Error on ID 36018_198822. Retrying... (429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 500, model: gemini-3.1-flash-lite
Please retry in 19.685941056s.)
  ✓ Processed ID: 36018_198822

All entries processed successfully!

In [ ]:
ANNOTATION_PROMPT = """\
You are a professional English→Japanese translation quality evaluator.

Given an English source sentence, a candidate Japanese translation, and a reference
Japanese translation, evaluate the candidate for errors.

### Error categories
1. **Terminology** – incorrect or inconsistent term usage
2. **Accuracy** – meaning additions, omissions, or distortions
3. **Fluency/Grammar** – unnatural phrasing, grammatical mistakes
4. **Style/Register** – inappropriate formality level or tone
5. **Locale/Formatting** – wrong number formats, date formats, punctuation conventions

### Severity
- **major** – the error changes meaning or seriously hinders comprehension
- **minor** – the error is noticeable but does not change core meaning
- **none** – no meaningful error detected

### Rules
- Do NOT penalise stylistic differences if the core meaning is preserved correctly.
- If `has_error` is false, `severity` MUST be "none" and `categories` MUST be [].
- Return ONLY valid JSON — no markdown fences, no explanation outside the JSON.

### Input
- **Source (EN):** {source_en}
- **Candidate (JA):** {candidate_ja}
- **Reference (JA):** {reference_ja}

### Required JSON output schema
{{
  "has_error": true | false,
  "severity": "major" | "minor" | "none",
  "categories": [],
  "rationale": "string"
}}
"""

print("Prompt template loaded. Placeholders: {source_en}, {candidate_ja}, {reference_ja}")

Prompt template loaded. Placeholders: {source_en}, {candidate_ja}, {reference_ja}

## 5. Verify Annotation Results

Load the Gemini-annotated JSONL and display the first few rows to confirm the annotations look correct.

In [4]:
import pandas as pd
from pathlib import Path

# Assuming OUTPUT_PATH is defined elsewhere, but re-defining for standalone execution if needed
# This path is based on previous cell outputs where `gemini_annotated_results.jsonl` is created.
OUTPUT_PATH = Path('/content/drive/MyDrive/GenAI Own/gemini_annotated_results.jsonl')

if not OUTPUT_PATH.exists():
    print(f"Error: The file {OUTPUT_PATH.name} does not exist at {OUTPUT_PATH.parent}.")
else:
    df_annotated_results = pd.read_json(OUTPUT_PATH, lines=True, dtype={'id': str})
    print(f"Successfully loaded {len(df_annotated_results)} annotations.")
    print("First 5 annotated results:")
    display(df_annotated_results.head(5))

Successfully loaded 499 annotations.
First 5 annotated results:

,id,source_en,reference_ja,candidate_ja,has_error,severity,categories,rationale
0,41423_204181,Don't keep company with such a bad boy.,そんな悪い子と友達になるな。,そんな不良と付き合わないでください。,False,none,[],The candidate translation accurately reflects ...
1,9354007_9678940,It wasn't our fault. Believe me.,私達のせいじゃないわ。信じてよ。,それは私たちの faultではありません。信じてください。,True,minor,[Terminology],The candidate leaves the English word 'fault' ...
2,71054_149509,May I ask you a question?,質問をしてもいいですか。,質問させていただけますか？,False,none,[],The candidate translation is grammatically cor...
3,264505_150052,"In his autobiography, he repeatedly refers to ...",自伝の中で彼はくりかえし不幸な少年時代に言及している。,彼の自伝では、彼は再三、不快な学校生活について言及しています。,True,minor,[Terminology],The term 'unhappy school days' is translated a...
4,9193501_11563342,The apple cake's ran out.,アップルケーキがなくなっちゃった。,APPLE ケーキがなくなりました。,True,minor,[Style/Register],Using half-width Latin characters for 'APPLE' ...